'use client';

import React, { useState } from 'react';
import { Sparkles, X, BookOpen, Check, Copy, Printer, Save } from 'lucide-react';
import { ProfPlanData, save, load } from '@/lib/store';

export default function AILessonPlanModal({
    isOpen,
    onClose,
    data,
}: {
    isOpen: boolean;
    onClose: () => void;
    data: ProfPlanData;
}) {
    const [selectedTopic, setSelectedTopic] = useState('');
    const [generating, setGenerating] = useState(false);
    const [lessonPlan, setLessonPlan] = useState<string | null>(null);
    const [copied, setCopied] = useState(false);
    const [savedToNotes, setSavedToNotes] = useState(false);

    if (!isOpen) return null;

    const handleGenerate = () => {
        if (!selectedTopic) return;
        setGenerating(true);
        setCopied(false);
        setSavedToNotes(false);

        // Simulated structured AI generation tailored for Odisha academics
        setTimeout(() => {
            setLessonPlan(`
# LESSON PLAN: ${selectedTopic}
**Generated by ProfPlan AI (APNSIR Foundation)**

### 1. Learning Objectives
* Students will understand the core definitions, theoretical framework, and historical context of ${selectedTopic}.
* Ability to apply conceptual knowledge to practical regional problem-solving and academic examinations.

### 2. Pedagogical Methodology
* Interactive lecture combined with bilingual explanation (Odia/English context suitability) for conceptual clarity.
* Real-world analogies suited for higher secondary (+2) and undergraduate (UG) students.

### 3. Classroom Activities (45 Mins)
* **Introduction & Hook (10 mins):** Engage students with an interactive real-world query or historical background.
* **Core Delivery (25 mins):** Systematic breakdown of theoretical principles, diagrams, or textual analysis.
* **Summary & Doubt Clearance (10 mins):** Interactive Q&A and formative concept check.

### 4. Assessment & Evaluation
* Short-form formative quiz and structured homework assignment.
            `.trim());
            setGenerating(false);
        }, 800);
    };

    const handleCopy = () => {
        if (!lessonPlan) return;
        navigator.clipboard.writeText(lessonPlan);
        setCopied(true);
        setTimeout(() => setCopied(false), 2500);
    };

    const handlePrint = () => {
        if (!lessonPlan) return;
        const printWindow = window.open('', '_blank');
        if (printWindow) {
            printWindow.document.write(`
                <html>
                    <head>
                        <title>ProfPlan AI Lesson Plan - ${selectedTopic}</title>
                        <style>
                            body { font-family: Arial, sans-serif; padding: 30px; color: #0f172a; line-height: 1.6; }
                            h1 { font-size: 20px; border-bottom: 2px solid #334155; padding-bottom: 10px; }
                            h3 { font-size: 14px; color: #1e3a8a; margin-top: 20px; }
                            ul { padding-left: 20px; }
                            li { margin-bottom: 6px; font-size: 13px; }
                            .footer { margin-top: 40px; font-size: 11px; color: #64748b; border-top: 1px solid #cbd5e1; pt: 10px; }
                        </style>
                    </head>
                    <body>
                        <h1>LESSON PLAN: ${selectedTopic}</h1>
                        <p><strong>APNSIR Foundation • E-Lesson Plan &amp; Progress Register</strong></p>
                        <div style="white-space: pre-wrap; font-size: 13px;">${lessonPlan}</div>
                        <div class="footer">Generated via ProfPlan AI Assistant for Educators of Odisha.</div>
                        <script>window.print();</script>
                    </body>
                </html>
            `);
            printWindow.document.close();
        }
    };

    const handleSaveToNotes = () => {
        if (!lessonPlan) return;
        try {
            const currentData = load();
            const newLog: any = {
                id: 'log_ai_' + Date.now(),
                date: new Date().toLocaleDateString('en-CA'),
                courseId: currentData.courses?.[0]?.id || 'general',
                plannedTopicName: selectedTopic,
                covered: `AI Lesson Plan: ${selectedTopic}`,
                status: 'completed' as const, // Type-safe status assignment matching Log union type
                hours: 1,
                remarks: lessonPlan.slice(0, 250) + '...',
                classSource: 'AI Assistant',
            };

            const updatedLogs = [...(currentData.logs || []), newLog];
            save({ ...currentData, logs: updatedLogs });
            setSavedToNotes(true);
            setTimeout(() => setSavedToNotes(false), 3000);
        } catch (err) {
            console.error('Failed to save AI lesson plan to notes:', err);
        }
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4 backdrop-blur-sm animate-in fade-in">
            <div className="w-full max-w-xl rounded-3xl bg-white p-6 md:p-7 shadow-2xl space-y-4 border border-slate-100 flex flex-col max-h-[90vh]">
                
                {/* MODAL HEADER */}
                <div className="flex items-center justify-between border-b border-slate-100 pb-3.5 shrink-0">
                    <div className="flex items-center gap-2.5">
                        <div className="p-2 bg-gradient-to-r from-amber-500 to-orange-600 rounded-xl text-white shadow-sm">
                            <Sparkles className="w-4 h-4" />
                        </div>
                        <div>
                            <h3 className="text-base font-black text-slate-900">AI Lesson Plan Assistant</h3>
                            <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">APNSIR Foundation Pedagogical Tool</p>
                        </div>
                    </div>
                    <button
                        type="button"
                        onClick={onClose}
                        className="p-2 rounded-xl text-slate-400 hover:bg-slate-100 transition cursor-pointer"
                    >
                        <X className="w-5 h-5" />
                    </button>
                </div>

                {/* MODAL BODY */}
                <div className="space-y-4 overflow-y-auto min-h-0 flex-1 pr-1">
                    <div>
                        <label className="block text-xs font-black uppercase tracking-wider text-slate-700 mb-1.5">
                            Enter Topic Title *
                        </label>
                        <div className="flex gap-2">
                            <input
                                type="text"
                                value={selectedTopic}
                                onChange={(e) => setSelectedTopic(e.target.value)}
                                placeholder="e.g. Time-Binding by Alfred Korzybski or Photosynthesis"
                                className="w-full rounded-xl border-2 border-slate-200 px-4 py-3 text-xs sm:text-sm font-semibold text-slate-900 outline-none focus:border-indigo-600 focus:ring-4 focus:ring-indigo-100 transition"
                            />
                            <button
                                type="button"
                                onClick={handleGenerate}
                                disabled={generating || !selectedTopic.trim()}
                                className="px-5 py-3 bg-indigo-600 hover:bg-indigo-700 text-white font-black text-xs uppercase tracking-wider rounded-xl shadow-md transition disabled:opacity-40 shrink-0 cursor-pointer"
                            >
                                {generating ? 'Synthesizing...' : 'Generate'}
                            </button>
                        </div>
                    </div>

                    {lessonPlan && (
                        <div className="space-y-3 animate-in fade-in">
                            <div className="max-h-64 overflow-y-auto rounded-2xl bg-slate-50 p-4 border border-slate-200 text-xs leading-relaxed text-slate-800 whitespace-pre-wrap font-medium shadow-inner">
                                {lessonPlan}
                            </div>

                            {/* ACTION BUTTON BAR */}
                            <div className="flex flex-wrap items-center gap-2 pt-1">
                                <button
                                    type="button"
                                    onClick={handleCopy}
                                    className="flex-1 inline-flex items-center justify-center gap-1.5 px-4 py-2.5 bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs rounded-xl shadow transition cursor-pointer"
                                >
                                    <Copy className="w-3.5 h-3.5 text-blue-300" />
                                    <span>{copied ? '✓ Copied to Clipboard!' : 'Copy Text'}</span>
                                </button>

                                <button
                                    type="button"
                                    onClick={handlePrint}
                                    className="inline-flex items-center justify-center gap-1.5 px-4 py-2.5 bg-blue-50 hover:bg-blue-100 text-blue-900 border border-blue-200 font-bold text-xs rounded-xl shadow-xs transition cursor-pointer"
                                    title="Print A4 Lesson Plan"
                                >
                                    <Printer className="w-3.5 h-3.5 text-blue-700" />
                                    <span>Print</span>
                                </button>

                                <button
                                    type="button"
                                    onClick={handleSaveToNotes}
                                    className="inline-flex items-center justify-center gap-1.5 px-4 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs rounded-xl shadow-xs transition cursor-pointer"
                                    title="Save into teaching notes database"
                                >
                                    <Save className="w-3.5 h-3.5" />
                                    <span>{savedToNotes ? '✓ Saved!' : 'Save to Notes'}</span>
                                </button>
                            </div>
                        </div>
                    )}
                </div>

                {/* MODAL FOOTER */}
                <div className="flex justify-end pt-3 border-t border-slate-100 shrink-0">
                    <button
                        type="button"
                        onClick={onClose}
                        className="px-5 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-extrabold text-xs rounded-xl transition cursor-pointer"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
}